/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'about': RouteRecordInfo<'about', '/about', Record<never, never>, Record<never, never>>,
    'accept-invite': RouteRecordInfo<'accept-invite', '/accept-invite', Record<never, never>, Record<never, never>>,
    'account-security': RouteRecordInfo<'account-security', '/account-security', Record<never, never>, Record<never, never>>,
    'admin-audit-log': RouteRecordInfo<'admin-audit-log', '/admin-audit-log', Record<never, never>, Record<never, never>>,
    'admin-contact-messages': RouteRecordInfo<'admin-contact-messages', '/admin-contact-messages', Record<never, never>, Record<never, never>>,
    'admin-invoices': RouteRecordInfo<'admin-invoices', '/admin-invoices', Record<never, never>, Record<never, never>>,
    'admin-messages': RouteRecordInfo<'admin-messages', '/admin-messages', Record<never, never>, Record<never, never>>,
    'admin-usage': RouteRecordInfo<'admin-usage', '/admin-usage', Record<never, never>, Record<never, never>>,
    'admin-wallet-credits': RouteRecordInfo<'admin-wallet-credits', '/admin-wallet-credits', Record<never, never>, Record<never, never>>,
    'channel-settings': RouteRecordInfo<'channel-settings', '/channel-settings', Record<never, never>, Record<never, never>>,
    'channels': RouteRecordInfo<'channels', '/channels', Record<never, never>, Record<never, never>>,
    'channels-sms': RouteRecordInfo<'channels-sms', '/channels-sms', Record<never, never>, Record<never, never>>,
    'customers': RouteRecordInfo<'customers', '/customers', Record<never, never>, Record<never, never>>,
    'customers-organization-id': RouteRecordInfo<'customers-organization-id', '/customers/:organizationId', { organizationId: ParamValue<true> }, { organizationId: ParamValue<false> }>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'delivery-status-rules': RouteRecordInfo<'delivery-status-rules', '/delivery-status-rules', Record<never, never>, Record<never, never>>,
    'dlt': RouteRecordInfo<'dlt', '/dlt', Record<never, never>, Record<never, never>>,
    'dlt-requests': RouteRecordInfo<'dlt-requests', '/dlt-requests', Record<never, never>, Record<never, never>>,
    'erpnext-sync-log': RouteRecordInfo<'erpnext-sync-log', '/erpnext-sync-log', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'invoices': RouteRecordInfo<'invoices', '/invoices', Record<never, never>, Record<never, never>>,
    'knowledge-base': RouteRecordInfo<'knowledge-base', '/knowledge-base', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'onboarding': RouteRecordInfo<'onboarding', '/onboarding', Record<never, never>, Record<never, never>>,
    'payment-reconciliation': RouteRecordInfo<'payment-reconciliation', '/payment-reconciliation', Record<never, never>, Record<never, never>>,
    'platform-erpnext-settings': RouteRecordInfo<'platform-erpnext-settings', '/platform-erpnext-settings', Record<never, never>, Record<never, never>>,
    'platform-general-settings': RouteRecordInfo<'platform-general-settings', '/platform-general-settings', Record<never, never>, Record<never, never>>,
    'platform-sms-settings': RouteRecordInfo<'platform-sms-settings', '/platform-sms-settings', Record<never, never>, Record<never, never>>,
    'platform-smtp-settings': RouteRecordInfo<'platform-smtp-settings', '/platform-smtp-settings', Record<never, never>, Record<never, never>>,
    'pricing': RouteRecordInfo<'pricing', '/pricing', Record<never, never>, Record<never, never>>,
    'privacy-policy': RouteRecordInfo<'privacy-policy', '/privacy-policy', Record<never, never>, Record<never, never>>,
    'provider-routes': RouteRecordInfo<'provider-routes', '/provider-routes', Record<never, never>, Record<never, never>>,
    'rate-cards': RouteRecordInfo<'rate-cards', '/rate-cards', Record<never, never>, Record<never, never>>,
    'refund-policy': RouteRecordInfo<'refund-policy', '/refund-policy', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'reports-activity-log': RouteRecordInfo<'reports-activity-log', '/reports/activity-log', Record<never, never>, Record<never, never>>,
    'reports-api-log': RouteRecordInfo<'reports-api-log', '/reports/api-log', Record<never, never>, Record<never, never>>,
    'reports-payment-ledger': RouteRecordInfo<'reports-payment-ledger', '/reports/payment-ledger', Record<never, never>, Record<never, never>>,
    'reports-purchase-ledger': RouteRecordInfo<'reports-purchase-ledger', '/reports/purchase-ledger', Record<never, never>, Record<never, never>>,
    'reports-wallet-ledger': RouteRecordInfo<'reports-wallet-ledger', '/reports/wallet-ledger', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'sms': RouteRecordInfo<'sms', '/sms', Record<never, never>, Record<never, never>>,
    'team': RouteRecordInfo<'team', '/team', Record<never, never>, Record<never, never>>,
    'terms-of-service': RouteRecordInfo<'terms-of-service', '/terms-of-service', Record<never, never>, Record<never, never>>,
    'users': RouteRecordInfo<'users', '/users', Record<never, never>, Record<never, never>>,
    'verify-account': RouteRecordInfo<'verify-account', '/verify-account', Record<never, never>, Record<never, never>>,
    'wallet': RouteRecordInfo<'wallet', '/wallet', Record<never, never>, Record<never, never>>,
  }
}
