"""Razorpay wallet recharge (test mode). Requires RAZORPAY_KEY_ID/RAZORPAY_KEY_SECRET from a
Razorpay account's test-mode API keys -- these are account-specific and cannot be generated by
this codebase; until they're set, these endpoints return a clear "not configured" error rather
than a confusing failure deep inside the Razorpay SDK.

Security: the amount credited always comes from the `PaymentOrder` row created server-side at
order-creation time, never from the client's post-checkout report -- this is what stops a client
from creating a small order and then claiming a larger amount was paid. The order id is bound to
the entity that created it, so one entity's order/payment cannot be replayed to credit another."""
import razorpay
from fastapi import APIRouter, Depends, HTTPException, Request
from sqlalchemy import select
from sqlalchemy.orm import Session

from .auth import require_user
from .config import settings
from .database import get_db
from .invoicing import create_draft_invoice, issue_invoice
from .models import PaymentOrder, User
from .schemas import RazorpayOrderRequest, RazorpayOrderResponse, RazorpayVerifyRequest, RechargeResponse
from .services import GST_RATE, DomainError, client_ip, credit_wallet, enforce_topup_integrity, quote_credits, require_channel_active, require_min_recharge, resolve_rate_card, resolve_user_entity

router = APIRouter(prefix="/v1/wallet/recharge/razorpay", tags=["wallet"])


def _client() -> razorpay.Client:
    if not settings.razorpay_key_id or not settings.razorpay_key_secret:
        raise HTTPException(status_code=503, detail="Razorpay is not configured. Set RAZORPAY_KEY_ID and RAZORPAY_KEY_SECRET (test-mode keys from your Razorpay dashboard) in .env.")
    return razorpay.Client(auth=(settings.razorpay_key_id, settings.razorpay_key_secret))


@router.post("/order", response_model=RazorpayOrderResponse)
def create_order(payload: RazorpayOrderRequest, request: Request, user: User = Depends(require_user), db: Session = Depends(get_db)):
    client = _client()
    try:
        entity = resolve_user_entity(db, user)
        require_channel_active(db, entity.id, "sms")
        rate_card = resolve_rate_card(db, user)
        require_min_recharge(rate_card, payload.amount)
        _credits, slab = quote_credits(db, rate_card, payload.amount)
    except DomainError as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc

    total_amount = payload.amount * (1 + GST_RATE)
    amount_paise = int(round(total_amount * 100))
    try:
        order = client.order.create({"amount": amount_paise, "currency": "INR", "receipt": f"wallet-{entity.id}", "notes": {"entity_id": entity.id, "pre_tax_amount": payload.amount}})
    except razorpay.errors.BadRequestError as exc:
        raise HTTPException(status_code=422, detail=f"Razorpay rejected the order request: {exc}") from exc

    # Snapshot the quoted rate now -- if an admin changes the rate card or a slab's
    # price_per_sms before the customer finishes checkout, they still get what they were quoted.
    db.add(PaymentOrder(
        entity_id=entity.id, provider="razorpay", provider_order_id=order["id"], amount=payload.amount, status="created",
        rate_card_id=rate_card.id, price_per_sms=slab.price_per_sms, user_id=user.id, ip_address=client_ip(request),
    ))
    db.commit()
    return RazorpayOrderResponse(order_id=order["id"], key_id=settings.razorpay_key_id, amount_paise=amount_paise)


@router.post("/verify", response_model=RechargeResponse)
def verify_payment(payload: RazorpayVerifyRequest, user: User = Depends(require_user), db: Session = Depends(get_db)):
    client = _client()
    try:
        entity = resolve_user_entity(db, user)
    except DomainError as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc

    # Row-locked so two concurrent /verify calls for the same order (a double-submit, or a
    # replayed request) serialize instead of both reading status=="created" and both crediting.
    order = db.scalar(select(PaymentOrder).where(PaymentOrder.provider_order_id == payload.razorpay_order_id, PaymentOrder.entity_id == entity.id).with_for_update())
    if not order:
        raise HTTPException(status_code=404, detail="No matching payment order for this account")
    if order.status != "created":
        raise HTTPException(status_code=409, detail=f"This order has already been {order.status}")

    try:
        client.utility.verify_payment_signature({
            "razorpay_order_id": payload.razorpay_order_id,
            "razorpay_payment_id": payload.razorpay_payment_id,
            "razorpay_signature": payload.razorpay_signature,
        })
    except razorpay.errors.SignatureVerificationError as exc:
        order.status = "failed"
        db.commit()
        raise HTTPException(status_code=422, detail="Payment signature verification failed") from exc

    try:
        if order.price_per_sms:
            # Use what was quoted at checkout, not whatever the rate card resolves to now.
            credits = float(order.amount) / float(order.price_per_sms)
        else:
            # Legacy order created before rate snapshotting existed -- fall back to a fresh
            # resolution rather than failing the payment.
            rate_card = resolve_rate_card(db, user)
            credits, _slab = quote_credits(db, rate_card, float(order.amount))
    except DomainError as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc

    wallet = credit_wallet(db, entity.id, credits, transaction_type="recharge_razorpay", reference=payload.razorpay_payment_id)
    order.status = "paid"
    order.credits_applied = credits
    gst_amount = round(float(order.amount) * GST_RATE, 2)
    price_per_sms = float(order.price_per_sms) if order.price_per_sms else (float(order.amount) / credits if credits else None)
    invoice = create_draft_invoice(db, entity, type="wallet_recharge", base_amount=float(order.amount), gst_amount=gst_amount, reference=order.id, credits_purchased=round(credits, 2), price_per_sms=price_per_sms)
    issue_invoice(db, invoice)

    # Independently re-verifies the credited amount matches what this order's own snapshotted
    # rate says it should be -- see enforce_topup_integrity's docstring for what this actually
    # protects against. A mismatch suspends the account and deactivates its API keys before this
    # transaction commits, so a bad credit never becomes spendable.
    if enforce_topup_integrity(db, order, entity, user, credits):
        db.commit()
        raise HTTPException(status_code=500, detail="A problem was detected with this transaction. Your account has been placed on hold pending review -- contact support.")

    db.commit()

    available = float(wallet.prepaid_balance) + max(0, float(wallet.credit_limit) - float(wallet.credit_used))
    return RechargeResponse(
        entity_id=entity.id,
        amount=float(order.amount),
        available_balance=available,
        credits_purchased=round(credits, 2),
        gst_amount=gst_amount,
        total_charged=round(float(order.amount) + gst_amount, 2),
    )
