"""Zoho Books is the source of truth for the invoice DOCUMENT itself -- once an organization has
been manually linked by an admin (link_organization, called from admin.py's POST .../zoho-sync;
never automatic), every issued invoice for it ensures the mapped Item exists, creates an Invoice,
resolves the correct GST tax (interstate IGST vs intrastate CGST+SGST, based on the customer's
state vs. the platform's own home state), marks it sent, records a Customer Payment if paid, and
fetches the rendered PDF back. Textzi's own fpdf2 rendering (invoicing.py's _render_invoice_pdf)
only ever runs as a fallback -- when the organization isn't linked yet, Zoho isn't configured at
all, or any step of this chain fails -- so a customer is never left with no invoice while a
failure gets retried later (admin.py's retry endpoint calls the exact same sync_invoice_to_zoho
used here). Every call is logged to ZohoApiCallLog, success or failure, so an admin can see
exactly what happened without digging through server logs.

Auth is OAuth2 self-client (api-console.zoho.com), not a static key/secret: an admin enters
client_id/client_secret once, then exchanges a one-time grant code (exchange_grant_code, called
from the admin "Connect" action) for a non-expiring refresh token. _access_token then keeps the
access token fresh automatically, refreshing it (and persisting the new one) whenever it's
expired or close to it -- callers never see this, they just get a valid token back."""
import hashlib
import json
import logging
from datetime import datetime, timedelta, timezone
from urllib.error import HTTPError
from urllib.parse import urlencode
from urllib.request import Request, urlopen

from sqlalchemy import text
from sqlalchemy.orm import Session

from .models import Invoice, Organization, PlatformZohoSettings, ZohoApiCallLog
from .security import decrypt_secret, encrypt_secret
from .services import INVOICE_TYPE_ITEM_GROUP, ITEM_GROUP_LABELS, ITEM_GROUP_SAC_CODES, get_platform_company_info, sac_code_for_invoice_type, state_code_from_gstin

logger = logging.getLogger("textzi.zoho_books")

# Three Zoho Items total, not one per Invoice.type -- "SMS Service" covers wallet_recharge and
# admin_credit; the two "Platform fee (...)" items each cover their own single invoice type
# (services.INVOICE_TYPE_ITEM_GROUP).
GROUP_ITEM_CODE_FIELDS = {
    "sms_service": "item_code_sms_service",
    "platform_fee_dlt": "item_code_platform_fee_dlt",
    "platform_fee_whatsapp": "item_code_platform_fee_whatsapp",
}

# A safety margin, not the literal expiry -- refreshing a few minutes early avoids a race where
# the token expires mid-sync (between _access_token returning it and the last HTTP call using it).
ACCESS_TOKEN_SAFETY_MARGIN_SECONDS = 300


class ZohoCallError(Exception):
    """Raised by _request/_fetch_invoice_pdf on any non-2xx response or connection failure --
    already logged to ZohoApiCallLog by the time it's raised."""


def get_zoho_settings(db: Session) -> PlatformZohoSettings | None:
    row = db.get(PlatformZohoSettings, "platform")
    if not row or not row.client_id or not row.client_secret_encrypted or not row.refresh_token_encrypted or not row.api_domain or not row.organization_id:
        return None
    return row


def _log(db: Session, invoice_id: str | None, method: str, path: str, status: str, status_code: int | None, error: str | None) -> None:
    db.add(ZohoApiCallLog(invoice_id=invoice_id, method=method, path=path, status=status, status_code=status_code, error=error[:500] if error else None))
    db.commit()


def exchange_grant_code(db: Session, grant_code: str) -> PlatformZohoSettings:
    """The one-time step that turns a pasted grant/authorization code (generated by an admin from
    api-console.zoho.com) into a permanent refresh token -- called exactly once per "Connect"
    click, never again afterward. accounts_domain and client_id/client_secret must already be
    saved (via PUT .../zoho-settings) before this can run."""
    row = db.get(PlatformZohoSettings, "platform")
    if not row or not row.client_id or not row.client_secret_encrypted or not row.accounts_domain:
        raise ZohoCallError("Set the client id, client secret, and accounts domain before connecting")
    url = f"https://{row.accounts_domain}/oauth/v2/token"
    query = {
        "grant_type": "authorization_code", "code": grant_code,
        "client_id": row.client_id, "client_secret": decrypt_secret(row.client_secret_encrypted),
    }
    full_url = url + "?" + urlencode(query)
    request = Request(full_url, method="POST", headers={"User-Agent": "Textzi-Zoho-Integration/1.0"})
    try:
        with urlopen(request, timeout=20) as response:
            result = json.loads(response.read().decode())
        _log(db, None, "POST", "/oauth/v2/token", "success", response.status, None)
    except HTTPError as exc:
        try:
            error_body = exc.read().decode(errors="replace")[:400]
        except OSError:
            error_body = ""
        message = f"HTTP {exc.code}: {error_body}" if error_body else f"HTTP {exc.code}"
        _log(db, None, "POST", "/oauth/v2/token", "failed", exc.code, message)
        raise ZohoCallError(message) from exc
    except Exception as exc:  # noqa: BLE001
        _log(db, None, "POST", "/oauth/v2/token", "failed", None, str(exc))
        raise ZohoCallError(str(exc)) from exc

    if "refresh_token" not in result or "access_token" not in result:
        raise ZohoCallError(f"Zoho did not return a refresh token -- check the grant code hasn't expired: {result}")
    row.refresh_token_encrypted = encrypt_secret(result["refresh_token"])
    row.access_token_encrypted = encrypt_secret(result["access_token"])
    row.access_token_expires_at = datetime.now(timezone.utc) + timedelta(seconds=int(result.get("expires_in", 3600)))
    if result.get("api_domain"):
        row.api_domain = result["api_domain"].removeprefix("https://").removeprefix("http://")
    db.commit()
    db.refresh(row)
    return row


def _access_token(db: Session, settings_row: PlatformZohoSettings) -> str:
    """Returns a valid access token, transparently refreshing (and persisting the new one) if the
    stored one is missing or close to expiry. Called once per sync_invoice_to_zoho/link_organization
    invocation, not once per HTTP call, so a single sync only ever refreshes at most once."""
    now = datetime.now(timezone.utc)
    if settings_row.access_token_encrypted and settings_row.access_token_expires_at:
        if settings_row.access_token_expires_at - timedelta(seconds=ACCESS_TOKEN_SAFETY_MARGIN_SECONDS) > now:
            return decrypt_secret(settings_row.access_token_encrypted)

    url = f"https://{settings_row.accounts_domain}/oauth/v2/token"
    query = {
        "grant_type": "refresh_token", "refresh_token": decrypt_secret(settings_row.refresh_token_encrypted),
        "client_id": settings_row.client_id, "client_secret": decrypt_secret(settings_row.client_secret_encrypted),
    }
    full_url = url + "?" + urlencode(query)
    request = Request(full_url, method="POST", headers={"User-Agent": "Textzi-Zoho-Integration/1.0"})
    try:
        with urlopen(request, timeout=20) as response:
            result = json.loads(response.read().decode())
        _log(db, None, "POST", "/oauth/v2/token", "success", response.status, None)
    except HTTPError as exc:
        try:
            error_body = exc.read().decode(errors="replace")[:400]
        except OSError:
            error_body = ""
        message = f"HTTP {exc.code}: {error_body}" if error_body else f"HTTP {exc.code}"
        _log(db, None, "POST", "/oauth/v2/token", "failed", exc.code, message)
        raise ZohoCallError(f"Could not refresh the Zoho access token: {message}") from exc
    except Exception as exc:  # noqa: BLE001
        _log(db, None, "POST", "/oauth/v2/token", "failed", None, str(exc))
        raise ZohoCallError(f"Could not refresh the Zoho access token: {exc}") from exc

    if "access_token" not in result:
        raise ZohoCallError(f"Zoho did not return an access token on refresh: {result}")
    settings_row.access_token_encrypted = encrypt_secret(result["access_token"])
    settings_row.access_token_expires_at = now + timedelta(seconds=int(result.get("expires_in", 3600)))
    db.commit()
    return result["access_token"]


def _request(db: Session, settings_row: PlatformZohoSettings, access_token: str, method: str, path: str, invoice_id: str | None, body: dict | None = None, query: dict | None = None) -> dict:
    query = dict(query or {})
    query["organization_id"] = settings_row.organization_id
    url = f"https://{settings_row.api_domain}/books/v3{path}?" + urlencode(query)
    headers = {
        "Authorization": f"Zoho-oauthtoken {access_token}", "Content-Type": "application/json", "Accept": "application/json",
        "User-Agent": "Textzi-Zoho-Integration/1.0",
    }
    data = json.dumps(body).encode() if body is not None else None
    request = Request(url, data=data, headers=headers, method=method)
    try:
        with urlopen(request, timeout=20) as response:
            result = json.loads(response.read().decode())
        _log(db, invoice_id, method, path, "success", response.status, None)
        return result
    except HTTPError as exc:
        try:
            error_body = exc.read().decode(errors="replace")[:400]
        except OSError:
            error_body = ""
        message = f"HTTP {exc.code}: {error_body}" if error_body else f"HTTP {exc.code}"
        _log(db, invoice_id, method, path, "failed", exc.code, message)
        raise ZohoCallError(message) from exc
    except Exception as exc:  # noqa: BLE001 -- must never leak an unanticipated exception type
        # past this boundary; see this module's own docstring.
        _log(db, invoice_id, method, path, "failed", None, str(exc))
        raise ZohoCallError(str(exc)) from exc


def list_tax_rates(db: Session, settings_row: PlatformZohoSettings) -> list[dict]:
    """Real configured tax rates/groups for the admin to pick the intrastate (CGST+SGST) and
    interstate (IGST) entries from -- fetched live rather than free-typed, since these are opaque
    Zoho tax_id GUIDs, not names."""
    access_token = _access_token(db, settings_row)
    result = _request(db, settings_row, access_token, "GET", "/settings/taxes", None)
    return result.get("taxes", [])


def list_accounts(db: Session, settings_row: PlatformZohoSettings) -> list[dict]:
    """Real Bank/Cash accounts from the chart of accounts, for the payment-deposit-account picker
    -- filtered to the account types a Customer Payment can actually deposit into."""
    access_token = _access_token(db, settings_row)
    result = _request(db, settings_row, access_token, "GET", "/chartofaccounts", None)
    accounts = result.get("chartofaccounts", [])
    return [a for a in accounts if a.get("account_type") in ("cash", "bank")]


def _find_contact(db: Session, settings_row: PlatformZohoSettings, access_token: str, field: str, value: str) -> dict | None:
    result = _request(db, settings_row, access_token, "GET", "/contacts", None, query={field: value})
    contacts = result.get("contacts") or []
    return contacts[0] if contacts else None


def link_organization(db: Session, organization: Organization) -> str:
    """The ONLY place a Zoho Contact ever gets created or linked -- called exclusively from the
    admin "Sync to Zoho" action (admin.py), never automatically from onboarding, complete-profile,
    or invoice issuance. Lookup is GSTIN-first (a government-issued unique identifier per legal
    business -- a match is unambiguously the same business regardless of what name/mobile Zoho
    has on file for it, and it's what actually drives GST correctness), falling back to email,
    falling back to creating a new Contact. On a GSTIN match, the existing contact's name/email/
    mobile are deliberately left untouched -- that record may reflect real accounting history
    predating this integration."""
    if organization.zoho_contact_id:
        return organization.zoho_contact_id

    settings_row = get_zoho_settings(db)
    if not settings_row:
        raise ZohoCallError("Zoho Books is not configured")
    access_token = _access_token(db, settings_row)

    if organization.gstin:
        existing = _find_contact(db, settings_row, access_token, "gst_no", organization.gstin)
        if existing:
            organization.zoho_contact_id = existing["contact_id"]
            db.commit()
            return organization.zoho_contact_id

    if organization.contact_email:
        existing = _find_contact(db, settings_row, access_token, "email", organization.contact_email)
        if existing:
            organization.zoho_contact_id = existing["contact_id"]
            db.commit()
            return organization.zoho_contact_id

    state_code = state_code_from_gstin(organization.gstin) or organization.state_code
    payload = {
        "contact_name": organization.name,
        "company_name": organization.name,
        "email": organization.contact_email,
        "gst_no": organization.gstin or None,
        "gst_treatment": "business_gst" if organization.gstin else "business_none",
        "place_of_contact": state_code,
    }
    result = _request(db, settings_row, access_token, "POST", "/contacts", None, body=payload)
    contact_id = result["contact"]["contact_id"]
    organization.zoho_contact_id = contact_id
    db.commit()
    return contact_id


def _find_item_by_name(db: Session, settings_row: PlatformZohoSettings, access_token: str, name: str) -> str | None:
    result = _request(db, settings_row, access_token, "GET", "/items", None, query={"name": name})
    items = result.get("items") or []
    return items[0]["item_id"] if items else None


def _ensure_item(db: Session, settings_row: PlatformZohoSettings, access_token: str, invoice_type: str, invoice_id: str) -> str:
    """Three Zoho Items total (not one per invoice TYPE) -- "SMS Service" for wallet_recharge/
    admin_credit, plus one "Platform fee (...)" item each for dlt_fee and channel_subscription
    (services.INVOICE_TYPE_ITEM_GROUP).
    Reuses the cached id on the settings row if already resolved; otherwise looks the item up by
    name first (it may already exist, created manually in Zoho by an admin) before creating one,
    same GSTIN-first-then-create-shaped discipline as link_organization. The admin only has to
    configure this once per group; it's never touched again after the first invoice of that type."""
    group = INVOICE_TYPE_ITEM_GROUP.get(invoice_type)
    field = GROUP_ITEM_CODE_FIELDS.get(group)
    if not field:
        raise ZohoCallError(f"No Zoho item group configured for invoice type '{invoice_type}'")
    item_id = getattr(settings_row, field, None)
    if item_id:
        return item_id

    label = ITEM_GROUP_LABELS[group]
    item_id = _find_item_by_name(db, settings_row, access_token, label)
    if not item_id:
        result = _request(db, settings_row, access_token, "POST", "/items", invoice_id, {
            "name": label,
            "rate": 0,
            # item_type governs which transaction types this item can appear on ("sales",
            # "purchases", "sales_and_purchases", "inventory") -- Textzi only ever sells these,
            # never purchases them. product_type is the separate goods-vs-service classification.
            "item_type": "sales",
            "product_type": "service",
            # Same SAC code Textzi's own PDF invoice prints for this invoice type
            # (services.sac_code_for_invoice_type) -- required for the line item's GST treatment.
            "hsn_or_sac": ITEM_GROUP_SAC_CODES[group],
        })
        item_id = result["item"]["item_id"]
    setattr(settings_row, field, item_id)
    db.commit()
    return item_id


def _resolve_tax_id(db: Session, settings_row: PlatformZohoSettings, customer_state: str | None) -> str:
    """Picks the interstate (IGST) tax_id when the customer's state differs from the platform's
    own registered home state (services.get_platform_company_info -- the same field the invoice
    PDF's seller block already uses), otherwise the intrastate (CGST+SGST) group. Only called when
    invoice.gst_amount > 0 -- an invoice type with no GST (e.g. admin_credit) never needs a tax_id
    at all, same as ERPNext's "leave taxes_and_charges empty" behavior."""
    home_state = get_platform_company_info(db).company_state_code
    is_interstate = bool(customer_state and home_state and customer_state != home_state)
    tax_id = settings_row.gst_tax_id_interstate if is_interstate else settings_row.gst_tax_id_intrastate
    if not tax_id:
        kind = "interstate (IGST)" if is_interstate else "intrastate (CGST+SGST)"
        raise ZohoCallError(f"GST amount is non-zero but no Zoho {kind} tax rate is configured")
    return tax_id


def _fetch_invoice_pdf(db: Session, settings_row: PlatformZohoSettings, access_token: str, zoho_invoice_id: str, invoice_id: str) -> bytes:
    path = f"/invoices/{zoho_invoice_id}"
    url = f"https://{settings_row.api_domain}/books/v3{path}?" + urlencode({"organization_id": settings_row.organization_id, "accept": "pdf"})
    headers = {"Authorization": f"Zoho-oauthtoken {access_token}", "User-Agent": "Textzi-Zoho-Integration/1.0"}
    request = Request(url, headers=headers, method="GET")
    try:
        with urlopen(request, timeout=30) as response:
            pdf_bytes = response.read()
        _log(db, invoice_id, "GET", path, "success", response.status, None)
        return pdf_bytes
    except HTTPError as exc:
        try:
            error_body = exc.read().decode(errors="replace")[:400]
        except OSError:
            error_body = ""
        message = f"HTTP {exc.code}: {error_body}" if error_body else f"HTTP {exc.code}"
        _log(db, invoice_id, "GET", path, "failed", exc.code, message)
        raise ZohoCallError(message) from exc
    except Exception as exc:  # noqa: BLE001
        _log(db, invoice_id, "GET", path, "failed", None, str(exc))
        raise ZohoCallError(str(exc)) from exc


def _mark_sent_if_needed(db: Session, settings_row: PlatformZohoSettings, access_token: str, current_status: str, zoho_invoice_id: str, invoice_id: str) -> None:
    """A freshly-created Invoice sits at status="draft", which is not a legally final GST document
    -- it must be marked sent to actually count. No-op if already non-draft, so this is safe to
    call from both the fresh-create path and a retry against an already-existing invoice."""
    if current_status != "draft":
        return
    _request(db, settings_row, access_token, "POST", f"/invoices/{zoho_invoice_id}/status/sent", invoice_id)


def _create_customer_payment(db: Session, settings_row: PlatformZohoSettings, access_token: str, customer_id: str, zoho_invoice_id: str, amount: float, reference: str | None, invoice_id: str) -> str:
    """Creates a Customer Payment reconciled against the given Invoice, so it shows as Paid in
    Zoho's own books instead of sitting outstanding forever. account_id (the Bank/Cash account
    actually receiving the money) is the one thing that must be configured -- Zoho has no way to
    infer that on its own."""
    if not settings_row.payment_deposit_account_id:
        raise ZohoCallError("This invoice is marked paid, but no Zoho payment deposit account is configured to reconcile it against")
    payload = {
        "customer_id": customer_id,
        "payment_mode": "banktransfer",
        "amount": amount,
        "date": datetime.now(timezone.utc).date().isoformat(),
        "reference_number": reference or zoho_invoice_id,
        "account_id": settings_row.payment_deposit_account_id,
        "invoices": [{"invoice_id": zoho_invoice_id, "amount_applied": amount}],
    }
    result = _request(db, settings_row, access_token, "POST", "/customerpayments", invoice_id, payload)
    return result["payment"]["payment_id"]


def _advisory_lock_key(invoice_id: str) -> int:
    """Deterministically maps an invoice id to a signed 64-bit int for pg_advisory_lock, so
    concurrent calls for the SAME invoice serialize on the SAME key."""
    return int.from_bytes(hashlib.sha256(invoice_id.encode()).digest()[:8], "big", signed=True)


def sync_invoice_to_zoho(db: Session, invoice: Invoice, organization: Organization) -> bytes | None:
    """The single entry point both issue_invoice() and the admin retry endpoint call. Returns the
    fetched PDF bytes on success (and leaves invoice.zoho_sync_status="synced"), or None on any
    failure (leaving invoice.zoho_sync_status="failed" with zoho_sync_error set) -- never raises,
    so a caller never needs its own try/except around this. If the organization hasn't been
    manually linked to Zoho yet (organization.zoho_contact_id is None), this returns None
    immediately with zero API calls and zoho_sync_status left as "pending" -- that's not a
    failure, the org just hasn't been activated."""
    if not organization.zoho_contact_id:
        invoice.zoho_sync_status = "pending"
        db.commit()
        return None

    # A session-level Postgres advisory lock, not a `SELECT ... FOR UPDATE` row lock -- this
    # function calls db.commit() several times internally (after recording zoho_invoice_id,
    # inside _ensure_item), and a row lock would be released by the first of those intermediate
    # commits, not held until this function returns. An advisory lock survives intermediate
    # commits on the same connection and is only released in the `finally` below, which is what
    # actually serializes two concurrent retries (or a retry racing issue_invoice) on the same
    # invoice.
    lock_key = _advisory_lock_key(invoice.id)
    db.execute(text("SELECT pg_advisory_lock(:key)"), {"key": lock_key})
    try:
        # Pick up zoho_invoice_id (or any other field) as it stands right now -- another call may
        # have committed changes to this same row while we were blocked above.
        db.refresh(invoice)

        settings_row = get_zoho_settings(db)
        if not settings_row:
            raise ZohoCallError("Zoho Books is not configured")
        access_token = _access_token(db, settings_row)
        customer_state = state_code_from_gstin(organization.gstin) or organization.state_code

        # A retry after a failure must never re-create the Invoice -- it already exists in Zoho at
        # this point (zoho_invoice_id was committed the moment creation succeeded, specifically so
        # a retry can tell). But the ORIGINAL failure could have been the total-mismatch check
        # below, not just the PDF fetch -- so this branch must re-verify the total against Zoho's
        # current state every time, not just skip straight to the PDF.
        if invoice.zoho_invoice_id:
            existing = _request(db, settings_row, access_token, "GET", f"/invoices/{invoice.zoho_invoice_id}", invoice.id)
            existing_data = existing.get("invoice", {})
            zoho_total = float(existing_data.get("total", 0))
            expected_total = float(invoice.total_amount)
            if abs(zoho_total - expected_total) > 0.005:
                raise ZohoCallError(
                    f"Zoho still records a different total (Rs {zoho_total:.2f}) than what was actually "
                    f"charged (Rs {expected_total:.2f}) for invoice {invoice.zoho_invoice_id} -- fix the "
                    f"invoice in Zoho directly (its tax rate/amount) before retrying.",
                )
            _mark_sent_if_needed(db, settings_row, access_token, existing_data.get("status", "draft"), invoice.zoho_invoice_id, invoice.id)
            if invoice.zoho_mark_paid and not invoice.zoho_payment_id:
                invoice.zoho_payment_id = _create_customer_payment(
                    db, settings_row, access_token, organization.zoho_contact_id, invoice.zoho_invoice_id,
                    expected_total, invoice.reference, invoice.id,
                )
                db.commit()
            pdf_bytes = _fetch_invoice_pdf(db, settings_row, access_token, invoice.zoho_invoice_id, invoice.id)
            invoice.zoho_sync_status = "synced"
            invoice.zoho_sync_error = None
            db.commit()
            return pdf_bytes

        item_id = _ensure_item(db, settings_row, access_token, invoice.type, invoice.id)

        line_item = {"item_id": item_id, "rate": float(invoice.base_amount), "quantity": 1, "hsn_or_sac": sac_code_for_invoice_type(invoice.type)}
        if float(invoice.gst_amount) > 0:
            line_item["tax_id"] = _resolve_tax_id(db, settings_row, customer_state)
        else:
            # Zoho requires a tax_id (or an explicit tax-exemption reason) on every line item once
            # GST compliance is enabled for the org -- confirmed live ("Specify either a Tax or Tax
            # Exemption") -- so a zero-GST invoice (e.g. a free/promotional admin_credit) still
            # needs a real 0% rate attached, not an omitted tax_id.
            if not settings_row.gst_tax_id_zero_rated:
                raise ZohoCallError("This invoice has no GST, but no Zoho zero-rate tax is configured")
            line_item["tax_id"] = settings_row.gst_tax_id_zero_rated
        payload = {
            "customer_id": organization.zoho_contact_id,
            "line_items": [line_item],
            "reference_number": invoice.invoice_number or invoice.id,
            "gst_no": organization.gstin or None,
            "gst_treatment": "business_gst" if organization.gstin else "business_none",
            "place_of_supply": customer_state or get_platform_company_info(db).company_state_code,
        }
        result = _request(db, settings_row, access_token, "POST", "/invoices", invoice.id, payload)
        zoho_invoice_id = result["invoice"]["invoice_id"]
        # Committed immediately -- before the total-mismatch check and the PDF fetch, both of
        # which can still fail on their own -- so a retry never risks creating a *second* Invoice
        # for the same Textzi invoice, even one that's already known to be wrong (see the mismatch
        # check right below: that invoice still exists in Zoho, just flagged). This matters even
        # more than it did for ERPNext, since Zoho has no server-side uniqueness on
        # reference_number at all -- nothing else would prevent a duplicate.
        invoice.zoho_invoice_id = zoho_invoice_id
        db.commit()

        # Never trust that "creation succeeded" means "the amount matches" -- Zoho computes its
        # own total server-side (tax rate lookup, rounding rules) independent of what was sent. If
        # it doesn't match what Textzi actually charged the customer, that's a sync failure
        # needing admin attention -- and the Zoho invoice just created is WRONG and needs manual
        # correction there, not a silently-accepted mismatch in the books.
        zoho_total = float(result["invoice"].get("total", 0))
        expected_total = float(invoice.total_amount)
        if abs(zoho_total - expected_total) > 0.005:
            raise ZohoCallError(
                f"Zoho recorded a different total (Rs {zoho_total:.2f}) than what was actually charged "
                f"(Rs {expected_total:.2f}) for invoice {zoho_invoice_id} -- likely a tax rate mismatch. "
                f"That Zoho invoice needs manual correction; check the configured GST tax rates.",
            )

        _mark_sent_if_needed(db, settings_row, access_token, result["invoice"].get("status", "draft"), zoho_invoice_id, invoice.id)
        if invoice.zoho_mark_paid and not invoice.zoho_payment_id:
            invoice.zoho_payment_id = _create_customer_payment(
                db, settings_row, access_token, organization.zoho_contact_id, zoho_invoice_id, expected_total, invoice.reference, invoice.id,
            )
            db.commit()
        pdf_bytes = _fetch_invoice_pdf(db, settings_row, access_token, zoho_invoice_id, invoice.id)
        invoice.zoho_sync_status = "synced"
        invoice.zoho_sync_error = None
        db.commit()
        return pdf_bytes
    except ZohoCallError as exc:
        invoice.zoho_sync_status = "failed"
        invoice.zoho_sync_error = str(exc)[:500]
        db.commit()
        logger.warning("zoho sync failed invoice_id=%s error=%s", invoice.id, exc)
        return None
    except Exception as exc:  # noqa: BLE001 -- must never leak past this boundary or crash the
        # caller (issue_invoice / the admin retry endpoint), same reasoning as _request's own
        # blanket catch. A 200 response that doesn't match the expected shape is exactly as much
        # "this sync attempt failed" as a network error or a 4xx/5xx, and must degrade the same
        # way: zoho_sync_status="failed" with a real error message, never an unhandled 500 while
        # the call log still shows the underlying HTTP call as a clean "success".
        invoice.zoho_sync_status = "failed"
        invoice.zoho_sync_error = f"Unexpected error parsing Zoho's response: {exc}"[:500]
        db.commit()
        logger.warning("zoho sync failed (unexpected) invoice_id=%s error=%s", invoice.id, exc)
        return None
    finally:
        db.execute(text("SELECT pg_advisory_unlock(:key)"), {"key": lock_key})
