export const COOKIE_MAX_AGE_1_YEAR = 365 * 24 * 60 * 60

// Mirrors apps/api/app/services.py's GST_STATE_CODES -- used to derive a customer's state for
// interstate (IGST) vs intrastate (CGST+SGST) determination when they have no GSTIN to derive it
// from (a GSTIN's own prefix is authoritative and takes priority whenever one is given).
export const GST_STATES = [
  { title: 'Jammu & Kashmir', value: '01' },
  { title: 'Himachal Pradesh', value: '02' },
  { title: 'Punjab', value: '03' },
  { title: 'Chandigarh', value: '04' },
  { title: 'Uttarakhand', value: '05' },
  { title: 'Haryana', value: '06' },
  { title: 'Delhi', value: '07' },
  { title: 'Rajasthan', value: '08' },
  { title: 'Uttar Pradesh', value: '09' },
  { title: 'Bihar', value: '10' },
  { title: 'Sikkim', value: '11' },
  { title: 'Arunachal Pradesh', value: '12' },
  { title: 'Nagaland', value: '13' },
  { title: 'Manipur', value: '14' },
  { title: 'Mizoram', value: '15' },
  { title: 'Tripura', value: '16' },
  { title: 'Meghalaya', value: '17' },
  { title: 'Assam', value: '18' },
  { title: 'West Bengal', value: '19' },
  { title: 'Jharkhand', value: '20' },
  { title: 'Odisha', value: '21' },
  { title: 'Chattisgarh', value: '22' },
  { title: 'Madhya Pradesh', value: '23' },
  { title: 'Gujarat', value: '24' },
  { title: 'Dadra & Nagar Haveli and Daman & Diu', value: '26' },
  { title: 'Maharashtra', value: '27' },
  { title: 'Karnataka', value: '29' },
  { title: 'Goa', value: '30' },
  { title: 'Lakshadweep', value: '31' },
  { title: 'Kerala', value: '32' },
  { title: 'Tamil Nadu', value: '33' },
  { title: 'Puducherry', value: '34' },
  { title: 'Andaman & Nicobar Islands', value: '35' },
  { title: 'Telangana', value: '36' },
  { title: 'Andhra Pradesh', value: '37' },
  { title: 'Ladakh', value: '38' },
  { title: 'Other Territory', value: '97' },
  { title: 'Centre Jurisdiction', value: '99' },
]
